#!/usr/bin/env bash
# Tool: deliver one story's artifacts to its app's target repo as a PR. SYNC mode, agent repo = source of truth.
#
#   ./push-artifacts.sh <app> <STORY_ID> [--body-file <file>] [--run-id <id>] [--dry-run]
#
# Syncs the story, test plan and test suite from this repo onto branch qa/<STORY_ID>-<slug> of the
# target repo (the story's tests folder is replaced wholesale, so deletions propagate), then opens
# or updates a PR into <targetBranch>. Infra is NOT pushed here (use bootstrap-target.sh for that).
# Requires the repo to be bootstrapped. Prints the PR URL on success. Reusable for any app/story.
set -u
QA_TOOL="push-artifacts"
. "$(dirname "$0")/scripts/qa-lib.sh"

DRY=0; BODY_FILE=""; RUN_ID=""; APP_ARG=""; STORY_ID=""
while [ $# -gt 0 ]; do
  case "$1" in
    --body-file) BODY_FILE="${2:?}"; shift 2;;
    --run-id) RUN_ID="${2:?}"; shift 2;;
    --dry-run) DRY=1; shift;;
    -h|--help) sed -n '2,12p' "$0" | sed 's/^# \{0,1\}//'; exit 0;;
    -*) qa_die "unknown option $1";;
    *) if [ -z "$APP_ARG" ]; then APP_ARG="$1"; elif [ -z "$STORY_ID" ]; then STORY_ID="$1"; else qa_die "unexpected arg $1"; fi; shift;;
  esac
done

qa_need jq; qa_need gh; qa_need git
qa_resolve "$APP_ARG"
[ -n "$STORY_ID" ] || qa_die "usage: ./push-artifacts.sh <app> <STORY_ID>"
qa_load_env

# Locate the story in the agent repo and derive its paths.
matches=(); for f in "$QA_ROOT"/apps/"$APP"/user-stories/"$STORY_ID"-*.md; do [ -f "$f" ] && matches+=("$f"); done
[ ${#matches[@]} -eq 1 ] || qa_die "expected exactly one apps/$APP/user-stories/$STORY_ID-*.md (found ${#matches[@]})"
STORY_FILE="${matches[0]}"
base="$(basename "$STORY_FILE" .md)"            # e.g. SCRUM-202-forms
SLUG="${base#"$STORY_ID"-}"                       # e.g. forms
heading="$(head -1 "$STORY_FILE")"               # "# User Story: SCRUM-202 - Account Sign-up Form"
TITLE="${heading#*- }"                            # strip up to the first "- " -> "Account Sign-up Form"
[ -n "$TITLE" ] && [ "$TITLE" != "$heading" ] || TITLE="$SLUG"
BRANCH="qa/$STORY_ID-$SLUG"
PR_TITLE="$STORY_ID: $TITLE E2E test suite"
REL_STORY="apps/$APP/user-stories/$base.md"
REL_PLAN="apps/$APP/specs/$STORY_ID-$SLUG-test-plan.md"
REL_TESTS="apps/$APP/tests/$SLUG"

[ -d "$QA_ROOT/$REL_TESTS" ] || qa_die "no test suite at $REL_TESTS — run the QA flow (steps 4-5) first"

echo "App:    $APP -> $TARGET_REPO ($TARGET_BRANCH)"
echo "Story:  $STORY_ID ($SLUG)  branch $BRANCH"
echo "Sync:   $REL_STORY, $REL_PLAN, $REL_TESTS/"

# Must be bootstrapped first.
qa_is_bootstrapped "$TARGET_REPO" "$APP" "$TARGET_BRANCH" \
  || qa_die "target not bootstrapped. Run: ./bootstrap-target.sh $APP"

if [ $DRY -eq 1 ]; then echo "(dry-run) would push the above onto $BRANCH and open/update a PR into $TARGET_BRANCH titled \"$PR_TITLE\""; exit 0; fi

tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
url="$(qa_clone_url "$TARGET_REPO")"
work="$tmp/repo"
git clone --depth 1 --branch "$TARGET_BRANCH" "$url" "$work" >/dev/null 2>&1 \
  || qa_die "could not clone $TARGET_REPO branch $TARGET_BRANCH"
cd "$work"

# Start the story branch from its remote state if it exists, else from targetBranch.
if git ls-remote --exit-code --heads origin "$BRANCH" >/dev/null 2>&1; then
  git fetch --depth 1 origin "$BRANCH" >/dev/null 2>&1
  git checkout -b "$BRANCH" FETCH_HEAD >/dev/null 2>&1
else
  git checkout -b "$BRANCH" >/dev/null 2>&1
fi

# Sync artifacts from the agent repo (source of truth): replace the story's files wholesale,
# so anything removed in the agent repo is removed on the branch too.
rm -rf "$work/$REL_TESTS" "$work/$REL_PLAN"
mkdir -p "$work/$(dirname "$REL_STORY")" "$work/$(dirname "$REL_PLAN")" "$work/$REL_TESTS"
cp "$QA_ROOT/$REL_STORY" "$work/$REL_STORY"
[ -f "$QA_ROOT/$REL_PLAN" ] && cp "$QA_ROOT/$REL_PLAN" "$work/$REL_PLAN"
cp -R "$QA_ROOT/$REL_TESTS/." "$work/$REL_TESTS/"

git add -A
if git diff --cached --quiet; then
  echo "branch already matches the agent repo — no new commit."
else
  msg="feat(tests): $STORY_ID $TITLE

Sync story, test plan and test suite from the QA agent repo.${RUN_ID:+
Run-ID: $RUN_ID}

Resolves $STORY_ID"
  qa_git commit -q -m "$msg"
  git push -u origin "$BRANCH" >/dev/null 2>&1 || qa_die "push to $BRANCH failed"
fi

# Open or update the PR.
body_args=()
if [ -n "$BODY_FILE" ] && [ -f "$BODY_FILE" ]; then body_args=(--body-file "$BODY_FILE")
else body_args=(--body "Automated E2E tests for $STORY_ID ($TITLE).${RUN_ID:+ Run-ID: $RUN_ID}

Results report is generated by CI (the run's Job Summary and the playwright-report artifact).")
fi

if gh pr view "$BRANCH" -R "$TARGET_REPO" >/dev/null 2>&1; then
  gh pr edit "$BRANCH" -R "$TARGET_REPO" --title "$PR_TITLE" "${body_args[@]}" >/dev/null 2>&1 || true
else
  gh pr create -R "$TARGET_REPO" --base "$TARGET_BRANCH" --head "$BRANCH" --title "$PR_TITLE" "${body_args[@]}" >/dev/null 2>&1 \
    || qa_die "gh pr create failed"
fi

PR_URL="$(gh pr view "$BRANCH" -R "$TARGET_REPO" --json url -q .url 2>/dev/null)"
echo "PR: ${PR_URL:-"(created/updated; URL unavailable)"}"
